apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: ui-event-logs
  namespace: dev
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "703671895821.dkr.ecr.eu-central-1.amazonaws.com/fleetconnect-dataplatform:spark-k8s"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/spark_runner.py"
  arguments:
    - "ui_event_logs"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: "1G"
    serviceAccount: spark-sa
    tolerations:
      - key: node-type
        operator: Equal
        value: "spark"
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                    - spark
    env:
      # Base environment variables
      - name: PYTHONPATH
        value: "/opt/spark/work-dir:/opt/spark/work-dir/src"
      - name: AWS_REGION
        value: "eu-central-1"
      
      # ConfigMap environment variables
      - name: ELASTIC_DB_URL
        valueFrom:
          configMapKeyRef:
            name: shared-config
            key: ELASTIC_DB_URL
      - name: ELASTIC_USERNAME
        valueFrom:
          configMapKeyRef:
            name: shared-config
            key: ELASTIC_USERNAME
      - name: KAFKA_BROKERS
        valueFrom:
          configMapKeyRef:
            name: shared-config
            key: KAFKA_BROKERS
      
      # Secret environment variables
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: password
      - name: DATABASE
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: fleet_db_database
      - name: DATABASE_HOST
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: dev_db_host
      - name: DATABASE_PORT
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: db_port
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: uraeus-elastic-search-es-elastic-user
            key: elastic
            
  executor:
    cores: 1
    instances: 1
    memory: "1G"
    tolerations:
      - key: node-type
        operator: Equal
        value: "spark"
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                    - spark
    env:
      # Base environment variables
      - name: PYTHONPATH
        value: "/opt/spark/work-dir:/opt/spark/work-dir/src"
      - name: AWS_REGION
        value: "eu-central-1"
      
      # ConfigMap environment variables
      - name: ELASTIC_DB_URL
        valueFrom:
          configMapKeyRef:
            name: shared-config
            key: ELASTIC_DB_URL
      - name: ELASTIC_USERNAME
        valueFrom:
          configMapKeyRef:
            name: shared-config
            key: ELASTIC_USERNAME
      - name: KAFKA_BROKERS
        valueFrom:
          configMapKeyRef:
            name: shared-config
            key: KAFKA_BROKERS
      
      # Secret environment variables
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: password
      - name: DATABASE
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: fleet_db_database
      - name: DATABASE_HOST
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: dev_db_host
      - name: DATABASE_PORT
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: db_port
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: uraeus-elastic-search-es-elastic-user
            key: elastic
            
  sparkConf:
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.endpoint": "s3.eu-central-1.amazonaws.com"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
    "spark.hadoop.fs.s3a.path.style.access": "false"
    "spark.driver.extraJavaOptions": "-Divy.home=/tmp/.ivy2 -Dokhttp.protocols=TLSv1.2 -Dhttp2.disable=true"
    "spark.executor.extraJavaOptions": "-Divy.home=/tmp/.ivy2 -Dokhttp.protocols=TLSv1.2 -Dhttp2.disable=true"
    "spark.kubernetes.submission.connectionTimeout": "60000"
    "spark.kubernetes.submission.requestTimeout": "60000"